version : "3.8"

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: "pg_vector"
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg_hm:/var/lib/postgresql/data

volumes:
  pg_hm: